--!native
--!optimize 2
local deh_misc = {}

deh_misc.deh_initial_health = 100
deh_misc.deh_initial_bullets = 50
deh_misc.deh_max_health = 200
deh_misc.deh_max_armor = 200
deh_misc.deh_green_armor_class = 1
deh_misc.deh_blue_armor_class = 2
deh_misc.deh_max_soulsphere = 200
deh_misc.deh_soulsphere_health = 100
deh_misc.deh_megasphere_health = 200
deh_misc.deh_god_mode_health = 100
deh_misc.deh_idfa_armor = 200
deh_misc.deh_idfa_armor_class = 2
deh_misc.deh_idkfa_armor = 200
deh_misc.deh_idkfa_armor_class = 2
deh_misc.deh_bfg_cells_per_shot = 40
deh_misc.deh_species_infighting = 0

return deh_misc